spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/medipet
    username: postgres
    password: changeme
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9093
          auto-create-topics: false
      bindings:
        emailTopicInputChannel:
          destination: emailTopic
          content-type: application/json
        emailTopicOutputChannel:
          destination: emailTopic
          content-type: application/json
  kafka:
    consumer:
      group-id: medipet
  application:
    name: medipet